events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    server {
        listen 80;
        server_name localhost;

        location = /cgit.css {
            root /usr/share/cgit;
        }

        location = /cgit.png {
            root /usr/share/cgit;
        }

        location = /favicon.ico {
            root /usr/share/cgit;
        }

        location / {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/libexec/cgit/cgit.cgi;
            fastcgi_param PATH_INFO $uri;
            fastcgi_param QUERY_STRING $args;
            fastcgi_param HTTP_HOST $server_name;
            fastcgi_pass unix:/run/fcgiwrap.sock;
        }
    }
}
