events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    server {
        listen 80 default_server;
        server_name _;

        location /cgit-css/ {
            alias /usr/share/cgit/;
        }

        location = /cgit.js {
            alias /usr/share/cgit/cgit.js;
        }

        location / {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/lib/cgit/cgit.cgi;
            fastcgi_param PATH_INFO $uri;
            fastcgi_param QUERY_STRING $args;
            fastcgi_param HTTP_HOST $http_host;
            fastcgi_pass unix:/run/fcgiwrap.sock;
        }
    }
}
