# Repositories to clone and render in cgit
# Format: <repo-name> <git-clone-url> [description] [owner] [shallow_depth]
# Use depth for massive repositories like linux (e.g. depth 50) so CI does not time out or run out of disk!

git-on-github local "git-on-github - A git repository wholly rendered by real cgit on GitHub Actions" "rebizzz"
linux https://github.com/torvalds/linux.git "Linux kernel source tree" "Linus Torvalds" 30
