# Repositories to clone and render in cgit
# Format: <repo-name> <git-clone-url> [description] [owner] [shallow_depth]

git-on-github https://github.com/rebizzz/git-on-github.git "git-on-github - A git repository wholly rendered by real cgit on GitHub Actions" "rebizzz" 50
cgit https://git.zx2c4.com/cgit "A hyperfast web frontend for git repositories written in C" "Jason A. Donenfeld" 50
curl https://github.com/curl/curl.git "A command line tool and library for transferring data with URLs" "Daniel Stenberg" 50
ripgrep https://github.com/BurntSushi/ripgrep.git "ripgrep combines the usability of The Silver Searcher with the raw speed of grep" "Andrew Gallant" 50
