export function renderLayout({ title, activeTab, repoInfo, content, rootPath = '', currentRef = 'HEAD' }) {
  const tabs = [
    { id: 'about', name: 'about', href: `${rootPath}about/index.html` },
    { id: 'summary', name: 'summary', href: `${rootPath}index.html` },
    { id: 'refs', name: 'refs', href: `${rootPath}refs/index.html` },
    { id: 'log', name: 'log', href: `${rootPath}log/index.html` },
    { id: 'tree', name: 'tree', href: `${rootPath}tree/${currentRef}/index.html` },
    { id: 'commit', name: 'commit', href: `${rootPath}commit/${repoInfo.headFull || 'HEAD'}.html` },
    { id: 'diff', name: 'diff', href: `${rootPath}diff/${repoInfo.headFull || 'HEAD'}.html` },
    { id: 'stats', name: 'stats', href: `${rootPath}stats/index.html` }
  ];

  const tabLinks = tabs.map(t => {
    const isActive = t.id === activeTab ? 'class="active"' : '';
    return `<a ${isActive} href="${t.href}">${t.name}</a>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang='en'>
<head>
<title>${escapeHtml(repoInfo.repoName)} - ${escapeHtml(title)}</title>
<meta name='generator' content='cgit v1.2.3-git-actions'/>
<meta name='robots' content='index, nofollow'/>
<link rel='stylesheet' type='text/css' href='${rootPath}cgit.css'/>
<link rel='alternate' title='${escapeHtml(repoInfo.repoName)} Atom feed' href='${rootPath}atom.xml' type='application/atom+xml'/>
</head>
<body>
<div id='cgit'>
<table id='header'>
<tr>
  <td class='logo' rowspan='2'><a href='${rootPath}index.html'><img src='https://git.zx2c4.com/cgit.png' alt='cgit logo'/></a></td>
  <td class='main'><a href='${rootPath}index.html'>index</a> : <a href='${rootPath}index.html'>${escapeHtml(repoInfo.repoName)}</a></td>
  <td class='form'>
    <form method='get'>
      <select name='h' onchange='window.location.href="${rootPath}tree/" + this.value + "/index.html"'>
        ${(repoInfo.branches || []).map(b => `<option value='${escapeHtml(b.name)}' ${b.name === currentRef ? 'selected' : ''}>${escapeHtml(b.name)}</option>`).join('')}
      </select>
    </form>
  </td>
</tr>
<tr>
  <td class='sub'>${escapeHtml(repoInfo.desc)}</td>
  <td class='sub right'>${escapeHtml(repoInfo.owner)}</td>
</tr>
</table>
<table class='tabs'><tr><td>
${tabLinks}
</td><td class='form'>
<form class='right' method='get' action='${rootPath}log/index.html'>
<select name='qt'>
<option value='grep'>log msg</option>
<option value='author'>author</option>
<option value='committer'>committer</option>
<option value='range'>range</option>
</select>
<input class='txt' type='search' size='10' name='q' value=''/>
<input type='submit' value='search'/>
</form>
</td></tr></table>
<div class='content'>
${content}
</div> <!-- class=content -->
<div class='footer'>generated by <a href='https://git.zx2c4.com/cgit/about/'>cgit v1.2.3</a> (<a href='https://git-scm.com/'>git</a>) on GitHub Actions</div>
</div> <!-- id=cgit -->
</body>
</html>`;
}

export function escapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
